### ISSUE TITLE
show() must be of the type array, null given

### ISSUE THREAD

**Issue by balzer82** [GaryJones/Gamajo-Dashboard-Glancer#12]
```
Uncaught TypeError: Argument 1 passed to Gamajo_Dashboard_Glancer::show() must be of the type array, null given, called in /var/www/vhosts/.../wp-includes/class-wp-hook.php on line 286 and defined in /var/www/vhosts/.../wp-content/plugins/portfolio-post-type/includes/class-gamajo-dashboard-glancer.php:85
Stack trace:
#0 /var/www/vhosts/.../wp-includes/class-wp-hook.php(286): Gamajo_Dashboard_Glancer->show(NULL)
#1 /var/www/vhosts/.../wp-includes/plugin.php(208): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/vhosts/.../wp-admin/includes/dashboard.php(317): apply_filters('dashboard_glanc...', Array)
#3 /var/www/vhosts/.../wp-admin/includes/template.php(1310): wp_dashboard_right_now('', Array)
#4 /var/www/vhosts/.../wp-admin/includes/dashboard.php(2
```

version: 1.0.0

**Comment by dikaso** [comment]
Same here.

WordPress: 5.3
Theme: NT Xeon Child (inačica 1.1.9)
Plugin: Portfolio Post Type (inačica 1.0.0)
PHP version: 7.2.18

```
Uncaught TypeError: Argument 1 passed to Gamajo_Dashboard_Glancer::show() must be of the type array, null given, called in /home/hobbybac/public_html/wp-includes/class-wp-hook.php on line 288 and defined in /home/hobbybac/public_html/wp-content/plugins/portfolio-post-type/includes/class-gamajo-dashboard-glancer.php:85
Stack trace:
#0 /home/hobbybac/public_html/wp-includes/class-wp-hook.php(288): Gamajo_Dashboard_Glancer->show(NULL)
#1 /home/hobbybac/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters(NULL, Array)
#2 /home/hobbybac/public_html/wp-admin/includes/dashboard.php(320): apply_filters('dashboard_glanc...', Array)
#3 /home/hobbybac/public_html/wp-admin/includes/template.php(1343): wp_dashboard_right_now('', Array)
#4 /home/hobbybac/public_html/wp-admin/includes/dashboard.php(232): do_meta_boxes(Object(WP_Screen), 'normal', '')
#5 /home/hobbybac/public_html/wp-admin/index.php(148): wp_dashboard()
#6 {main}
  thrown
```
